sudo: false
language: ruby
rvm:
- 2.4.0
before_install: gem install bundler -v 1.13.6
scripts:
- bundle exec rake
- bundle exec rake build
deploy:
  provider: rubygems
  api_key:
    secure: BJB04C+ol+AgUZpSXYaXP8Ifgju54ppZS1i94R3KNXK/9kiztEDE5bWGWs4fX8S3L23OAuSd2qRNYsNNoXYILrQjfrRPo8t5g8NgSCH5WUlimwk17P0Aj8zu18t6V09AI4Ym/tdK1b7Jfo/55mqADXyRNicQMV/A6znt35f3G9iYkoTuDAvfALW6sHi9xihuO5DC42TAniciTo5Wve6LpoqwzYypUIjsy3HE4C++goS49in/6gZg7bzLXyaZRX1VRAODbyLxT1An0WSpZxVSvkGBsBd5rXTy5pfMQCCye1qfvZ80TorhUsaOBgc19TaKKVoQWTsToLzZ+BZVJyXZ1wYRssth/tr0TA6QbI1JR3ld59GW31zQijFG81E+VGLAlP0mVuEaDeEn3bwcQb4Oy4QZpKnw4rUOHL721eGNS6N52kQFh+geBusiOdHm6LNrToarXTeEgesQf82yxFmgOheJu762Vr6fC5QUHkFd+V/zJPwHScz5NmOsVWTAFibheHLDdJsWUQyh+yRZ5xbdGuU2uAYxgyRwHgxii/f16QmXRkKmWdQgMjVmzGL07rFTpDWDoci5YrWvp+h34LXzdX1P0cmEnGGFryyck3iSwh5BOhripZaOg5cPjulgV+zYE3pT9QIVQ9JKbWbRz1Pm5ePV0ruyr0WJZCU3eab1oJU=
  gem: ruactor
  on:
    tags: true
    repo: TimWSpence/ruactor
